name: CI NextJS app through Github Actions
on:
    pull_request:
        branches:
            - main
            - stage
            - qa
            - development
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 18.x
              uses: actions/setup-node@v1
              with:
                  node-version: 18.x

            - name: Setup
              run: npm ci

            - name: Test
              run: |
                  npm run test:ci

